modLoader = "javafml"
# Change NeoForge Loader Version here(version migrate)
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/StarCarefree/OpenLink/issues"
license = "MIT"

[[mods]]
modId = "openlink"
version = "${version}"
displayName = "OpenLink"
authors = "StarCarefree, Terry_MC, zirranYa"
description = '''
Bring you a unique Minecraft Multiplayer playing experience OvO
'''
logoFile = "icon.png"

[[dependencies.openlink]]
modId = "neoforge"
type="required"
# And here
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink]]
modId = "minecraft"
type="required"
# Change Minecraft Version here(version migrate)
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "openlink.mixins.json"